apiVersion: seaweed.seaweedfs.com/v1
kind: SeaweedCSIDriver
metadata:
  name: seaweedfs
  namespace: seaweedfs-csi-driver
spec:
  # Mount an operator-managed Seaweed cluster in the same namespace.
  seaweedRef:
    name: seaweed-sample
    namespace: seaweedfs
  driverName: seaweedfs-csi-driver
  storageClass:
    name: seaweedfs
    isDefaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      replication: "000"