apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-csi-driver
  namespace: seaweedfs-csi-driver
spec:
  interval: 1h
  chart:
    spec:
      chart: seaweedfs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi-driver
        namespace: seaweedfs-csi-driver
  values:
    seaweedfsFiler: "seaweed-sample-filer.seaweedfs.svc.cluster.local:8888"