resources:
  - s3-identity.yaml
  - s3-credentials.yaml
  - s3-policy.yaml
  - s3-policybinding.yaml
  - test-app-namespace.yaml
  - test-app-deployment.yaml
  - test-app-pvc.yaml
namespace: test-app
