apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - seaweedfs-namespace.yaml
  - seaweedfs-filer-network-policy.yaml
  - seaweedfs-s3-network-policy.yaml
  - seaweedfs-master-network-policy.yaml
  - seaweedfs-seaweed.yaml
  - seaweedfs-rrg-csi-driver.yaml
  - seaweedfs-rrg-test-app.yaml
