apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-sample
  namespace: seaweedfs
spec:
  image: chrislusf/seaweedfs:latest
  hostSuffix: seaweed.abcdefg.com
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
    defaultReplication: "001"   # 2 copies, on 2 different servers
  volume:
    replicas: 0
    kind: DaemonSet
    hostPath:
      - path: /var/lib/seaweedfs/data0
        maxVolumeCount: 0 #Fill
    extraArgs:
      - "-ip.bind=0.0.0.0" # To allow port forwarding from the host to the container
  filer:
    replicas: 2
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
  s3:
    replicas: 1