apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata: 
  name: alice-intruder-creds
  namespace: test-app-intruder
spec:
  seaweedRef: 
    name: seaweed-sample
    namespace: seaweedfs
  identityRef: 
    name: alice-intruder
  secretRef: 
    name: alice-s3-secret
    namespace: test-app-intruder   # accessKeyField/secretKeyField default to accessKey/secretKey