apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: test-app-intruder
    namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/seaweedfs-cluster/test-app-intruder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: test-app
      namespace: flux-system
